version: "3.9"
services:
  web1:
    build: .
    ports:
      - "8081:8080"
  web2:
    build: .
    ports:
      - "8082:8080"
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx, '-g', 'daemon off;' ]
    ports:
        - "8090:80"